# Generated by Django 5.2.1 on 2025-12-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_delivery_address_order_delivery_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Beklemede"),
                    ("ONAY", "Hazırlanıyor"),
                    ("COMPLETED", "Tamamlandı"),
                    ("RED", "Reddedildi"),
                    ("IPTAL", "İptal Edildi"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Beklemede"),
                    ("ONAY", "Hazırlanıyor"),
                    ("COMPLETED", "Tamamlandı"),
                    ("RED", "Reddedildi"),
                    ("IPTAL", "İptal Edildi"),
                ],
                max_length=20,
            ),
        ),
    ]
